pipeline {
    agent any

    environment {
        CI = 'true'
        DOCKER_IMAGE = 'mpsean/hummingbird-signin-frontend'
    }
    stages {
        stage('Install Dependencies') {
            steps {
                sh 'docker run --rm --user "$(id -u):$(id -g)" -e CI=${CI} -v "$PWD":/app -w /app node:20-bookworm npm ci'
            }
        }
        stage('Test') {
            steps {
                sh 'docker run --rm --user "$(id -u):$(id -g)" -e CI=${CI} -v "$PWD":/app -w /app node:20-bookworm sh ./jenkins/scripts/test.sh'
            }
        }
        stage('Build Application') {
            steps {
                sh 'docker run --rm --user "$(id -u):$(id -g)" -e CI=${CI} -v "$PWD":/app -w /app node:20-bookworm npm run build'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -f .Dockerfile -t ${DOCKER_IMAGE}:${BUILD_NUMBER} -t ${DOCKER_IMAGE}:latest .'
            }
        }
        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKERHUB_USERNAME', passwordVariable: 'DOCKERHUB_TOKEN')]) {
                    sh './jenkins/scripts/deliver.sh'
                }
            }
        }
    }
}
